[[language]]
name = "c"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "make"
indent = { tab-width = 4, unit = "\t" }

[[language]]
name = "markdown"
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "java"
indent = { tab-width = 4, unit = "    " }

# MacOS only to fix clangd frankenstein fallback
# For posterity, also add the following to ~/Library/Preferences/clangd/config.yaml:
# CompileFlags:
#   Compiler: /run/current-system/sw/bin/clang++
[language-server.clangd]
command = "clangd"
args = ["--query-driver=/run/current-system/sw/bin/clang++"]
